
import { useState, useEffect } from "react";
import { useSearchParams } from "react-router-dom";
import { getClientQuotations, updateClientQuotationStatus, getClientQuotationById, getClientQuotationReport, getClientQuotationItemsReport } from "../services/salesService";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";
import { FaPlus, FaSearch, FaEye, FaEdit, FaPaperPlane, FaCheck, FaFileExcel, FaTimes } from "react-icons/fa";
import ClientQuotationModal from "../components/sales/ClientQuotationModal";
import UpdateGstModal from "../components/sales/UpdateGstModal";
import ClientQuotationDetailsModal from "../components/sales/ClientQuotationDetailsModal";
import ProductSelector from "../components/common/ProductSelector";
import ConfirmDialog from "../components/ui/ConfirmDialog";
import AlertToast from "../components/ui/AlertToast";

const ClientQuotation = () => {
    const [searchText, setSearchText] = useState("");
    const [quotations, setQuotations] = useState([]);
    const [loading, setLoading] = useState(false);
    const [totalCount, setTotalCount] = useState(0);
    const [nextPage, setNextPage] = useState(null);
    const [prevPage, setPrevPage] = useState(null);
    const [currentPage, setCurrentPage] = useState(1);
    const [isModalOpen, setIsModalOpen] = useState(false);

    // GST Modal State
    const [gstModalOpen, setGstModalOpen] = useState(false);
    const [selectedQuotation, setSelectedQuotation] = useState(null);

    // View Modal State
    const [viewModalOpen, setViewModalOpen] = useState(false);

    // Confirm Dialog State
    const [confirmOpen, setConfirmOpen] = useState(false);
    const [confirmAction, setConfirmAction] = useState(null);
    const [confirmMessage, setConfirmMessage] = useState("");
    const [confirmConfig, setConfirmConfig] = useState({});

    // Alert State
    const [alert, setAlert] = useState({ open: false, type: "success", message: "" });
    // Report Modal State
    const [showReportModal, setShowReportModal] = useState(false);
    const [downloading, setDownloading] = useState(false);
    const [reportFilters, setReportFilters] = useState({
        start_date: '',
        end_date: '',
        status: '',
        reportType: 'quotation_summary',
        product: ''
    });

    const [statusFilter, setStatusFilter] = useState("");
    const [searchParams] = useSearchParams();

    const handleOpenReport = () => {
        const now = new Date();
        const firstDay = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0];
        const today = now.toISOString().split('T')[0];
        setReportFilters({
            start_date: firstDay,
            end_date: today,
            status: '',
            reportType: 'quotation_summary',
            product: ''
        });
        setShowReportModal(true);
    };

    const generateReport = async () => {
        setDownloading(true);
        try {
            if (reportFilters.reportType === 'quotation_summary') {
                const reportData = await getClientQuotationReport(reportFilters);
                const wb = XLSX.utils.book_new();

                // 1. Summary Sheet
                const summaryData = [
                    ["SALES QUOTATION REPORT"],
                    [],
                    ["Generated By:", reportData.generated_by],
                    ["Generated At:", new Date(reportData.generated_at).toLocaleString()],
                    ["Date Range:", `${reportData.date_range?.start_date} to ${reportData.date_range?.end_date}`],
                    [],
                    ["SUMMARY STATISTICS"],
                    ["Total Quotations:", reportData.summary?.total_quotations || 0],
                    ["Total Value:", reportData.summary?.total_value || 0],
                    ["Accepted:", reportData.summary?.accepted_quotations || 0],
                    ["Draft:", reportData.summary?.draft_quotations || 0],
                    ["Sent:", reportData.summary?.sent_quotations || 0],
                    ["Rejected:", reportData.summary?.rejected_quotations || 0],
                    ["Acceptance Rate:", `${reportData.summary?.acceptance_rate}%`],
                    [],
                    ["TAX SUMMARY"],
                    ["CGST:", reportData.summary?.tax_collected?.cgst],
                    ["SGST:", reportData.summary?.tax_collected?.sgst],
                    ["IGST:", reportData.summary?.tax_collected?.igst],
                    ["Total Tax:", reportData.summary?.tax_collected?.total]
                ];
                // Add Quotation List to Summary Sheet
                if (reportData.quotations && reportData.quotations.length > 0) {
                    summaryData.push([]);
                    summaryData.push(["QUOTATION DETAILS"]);
                    summaryData.push(["Quotation No", "Date", "Client", "Query No", "Status", "Items", "Subtotal", "Tax", "Total Amount", "Validity", "Created By"]);

                    reportData.quotations.forEach(q => {
                        summaryData.push([
                            q.quotation_number,
                            q.quotation_date,
                            q.client_name,
                            q.query_number,
                            q.status,
                            q.total_items,
                            q.subtotal,
                            q.tax_summary?.total_tax || 0,
                            q.total_amount,
                            q.validity_date,
                            q.created_by
                        ]);
                    });
                } else {
                    summaryData.push([]);
                    summaryData.push(["No quotations found for this period."]);
                }

                const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
                XLSX.utils.book_append_sheet(wb, wsSummary, "Sales Quotation Report");

                const buffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
                const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8" });
                saveAs(blob, `Sales_Quotation_Report_${reportFilters.start_date}_to_${reportFilters.end_date}.xlsx`);
            } else {
                // Item Analysis Report
                const reportData = await getClientQuotationItemsReport({
                    start_date: reportFilters.start_date,
                    end_date: reportFilters.end_date,
                    product: reportFilters.product
                });

                const wb = XLSX.utils.book_new();

                // 1. Summary Sheet
                const summaryData = [
                    ["QUOTATION ITEMS ANALYSIS REPORT"],
                    [],
                    ["Generated At:", new Date(reportData.generated_at).toLocaleString()],
                    ["Date Range:", `${reportData.date_range?.start_date} to ${reportData.date_range?.end_date}`],
                    [],
                    ["SUMMARY STATISTICS"],
                    ["Total Items Quoted:", reportData.summary?.total_items || 0],
                    ["Total Quantity:", reportData.summary?.total_quantity || 0],
                    ["Total Value:", reportData.summary?.total_value || 0],
                    ["Stock Items:", reportData.summary?.stock_items || 0],
                    ["Manual Items:", reportData.summary?.manual_items || 0],
                    [],
                    ["TOP TRADED PRODUCTS"],
                    ["Item Code", "Item Name", "Total Qty", "Total Value", "Quotations Count"]
                ];

                if (reportData.top_products && reportData.top_products.length > 0) {
                    reportData.top_products.forEach(p => {
                        summaryData.push([
                            p.item_code,
                            p.item_name,
                            p.total_quantity,
                            p.total_value,
                            p.quotations_count
                        ]);
                    });
                } else {
                    summaryData.push(["No top products data unavailable"]);
                }

                const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
                XLSX.utils.book_append_sheet(wb, wsSummary, "Summary Analysis");

                // 2. Details Sheet
                const detailsData = [
                    ["QUOTATION ITEM DETAILS"],
                    [],
                    ["Quotation No", "Date", "Client", "Item Code", "Item Name", "Description", "HSN", "Quantity", "Unit", "Rate", "Amount", "From Stock"]
                ];

                if (reportData.quotations && reportData.quotations.length > 0) {
                    reportData.quotations.forEach(item => {
                        detailsData.push([
                            item.quotation_number,
                            item.quotation_date,
                            item.client_name,
                            item.item_code,
                            item.item_name,
                            item.description,
                            item.hsn_code,
                            item.quantity,
                            item.unit,
                            item.rate,
                            item.amount,
                            item.from_stock ? "Yes" : "No"
                        ]);
                    });
                } else {
                    detailsData.push(["No items found for this period."]);
                }

                const wsDetails = XLSX.utils.aoa_to_sheet(detailsData);
                XLSX.utils.book_append_sheet(wb, wsDetails, "Item Details");

                const buffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
                const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8" });
                saveAs(blob, `Quotation_Items_Analysis_${reportFilters.start_date}_to_${reportFilters.end_date}.xlsx`);
            }

            setShowReportModal(false);
        } catch (error) {
            console.error("Failed to generate report", error);
            setAlert({ open: true, type: "error", message: "Failed to generate report" });
        } finally {
            setDownloading(false);
        }
    };

    useEffect(() => {
        const viewId = searchParams.get("view_id");
        const statusParam = searchParams.get("status");

        if (statusParam) {
            setStatusFilter(statusParam);
        }

        if (viewId) {
            const fetchQuotation = async () => {
                try {
                    const data = await getClientQuotationById(viewId);
                    if (data) {
                        setSelectedQuotation(data);
                        setViewModalOpen(true);
                    }
                } catch (err) {
                    console.error("Failed to load quotation details", err);
                }
            };
            fetchQuotation();
        }
    }, [searchParams]);

    const fetchQuotations = async (page = 1, search = "", status = "") => {
        setLoading(true);
        try {
            const data = await getClientQuotations(page, search, status);
            setQuotations(data.results || []);
            setTotalCount(data.count || 0);
            setNextPage(data.next);
            setPrevPage(data.previous);
        } catch (error) {
            console.error("Failed to fetch quotations", error);
        } finally {
            setLoading(false);
        }
    };

    const handleStatusUpdate = (id, status) => {
        setConfirmMessage(`Are you sure you want to mark this quotation as ${status}?`);
        setConfirmConfig({
            icon: status === 'SENT' ? FaPaperPlane : (status === 'REJECTED' ? FaTimes : FaCheck),
            confirmButtonClass: status === 'SENT' ? "bg-indigo-600 hover:bg-indigo-700" : (status === 'REJECTED' ? "bg-red-600 hover:bg-red-700" : "bg-green-600 hover:bg-green-700"),
            iconBgClass: status === 'SENT' ? "bg-indigo-100 text-indigo-600" : (status === 'REJECTED' ? "bg-red-100 text-red-600" : "bg-green-100 text-green-600"),
            confirmText: status === 'SENT' ? "Send Quotation" : (status === 'REJECTED' ? "Reject Quotation" : "Accept Quotation")
        });

        setConfirmAction(() => async () => {
            try {
                await updateClientQuotationStatus(id, status);
                fetchQuotations(currentPage, searchText, statusFilter);
                setAlert({ open: true, type: "success", message: `Quotation marked as ${status}` });
            } catch (error) {
                setAlert({ open: true, type: "error", message: "Failed to update status" });
            } finally {
                setConfirmOpen(false);
            }
        });
        setConfirmOpen(true);
    };

    useEffect(() => {
        const timer = setTimeout(() => {
            fetchQuotations(currentPage, searchText, statusFilter);
        }, 500);
        return () => clearTimeout(timer);
    }, [searchText, currentPage, statusFilter]);

    const handleSearch = (e) => {
        setSearchText(e.target.value);
        setCurrentPage(1);
    };

    const handleNext = () => {
        if (nextPage) setCurrentPage((prev) => prev + 1);
    };

    const handlePrev = () => {
        if (prevPage) setCurrentPage((prev) => prev - 1);
    };

    return (
        <div>
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
                {/* HEADER */}
                <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
                    <div>
                        <h3 className="font-bold text-slate-800">Client Quotations</h3>
                        <span className="text-sm text-slate-500 font-semibold">
                            Total: {totalCount}
                        </span>
                    </div>

                    <div className="flex items-center gap-3">
                        <button
                            onClick={handleOpenReport}
                            className="flex items-center gap-2 px-4 py-2 bg-emerald-600 text-white text-sm font-semibold rounded-lg hover:bg-emerald-500"
                        >
                            <FaFileExcel className="text-sm" />
                            Download Report
                        </button>
                        <button
                            onClick={() => setIsModalOpen(true)}
                            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-500"
                        >
                            <FaPlus className="text-xs" />
                            New Quotation
                        </button>
                    </div>
                </div>

                {/* SEARCH & FILTER */}
                <div className="px-6 py-4 border-b border-slate-100 bg-slate-50">
                    <div className="flex flex-wrap gap-4 items-end">
                        <div className="w-40">
                            <label className="block text-xs font-semibold text-slate-600 mb-1">
                                Status
                            </label>
                            <select
                                value={statusFilter}
                                onChange={(e) => setStatusFilter(e.target.value)}
                                className="input w-full"
                            >
                                <option value="">All Status</option>
                                <option value="DRAFT">Draft</option>
                                <option value="SENT">Sent</option>
                                <option value="ACCEPTED">Accepted</option>
                                <option value="REJECTED">Rejected</option>
                            </select>
                        </div>
                        <div className="flex-1 min-w-55">
                            <label className="block text-xs font-semibold text-slate-600 mb-1">
                                Search Quotation
                            </label>
                            <div className="relative">
                                <input
                                    value={searchText}
                                    onChange={handleSearch}
                                    placeholder="Search by number, client..."
                                    className="w-full pl-10 pr-4 py-2 bg-white border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                                />
                                <FaSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                            </div>
                        </div>
                    </div>
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-blue-50/50 text-slate-800 uppercase text-[10px] font-bold tracking-widest">
                                <th className="px-6 py-4 text-[13px]">Quotation No</th>
                                <th className="px-6 py-4 text-[13px]">Date</th>
                                <th className="px-6 py-4 text-[13px]">Client</th>
                                <th className="px-6 py-4 text-[13px]">Query No</th>
                                <th className="px-6 py-4 text-[13px] text-right">Amount</th>
                                <th className="px-6 py-4 text-[13px]">Status</th>
                                <th className="px-6 py-4 text-[13px] text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {loading ? (
                                <tr>
                                    <td colSpan="7" className="px-6 py-6 text-center text-slate-500">
                                        Loading...
                                    </td>
                                </tr>
                            ) : quotations.length > 0 ? (
                                quotations.map((item) => (
                                    <tr key={item.id} className="hover:bg-slate-50/50 transition-colors">
                                        <td className="px-6 py-4 font-mono text-blue-600 font-semiboldb">
                                            {item.quotation_number}
                                        </td>
                                        <td className="px-6 py-4 text-sm text-slate-600">
                                            {item.quotation_date}
                                        </td>
                                        <td className="px-6 py-4 text-sm font-medium text-slate-800">
                                            {item.client_name}
                                        </td>
                                        <td className="px-6 py-4 text-sm text-slate-500 font-mono">
                                            {item.query_number}
                                        </td>
                                        <td className="px-6 py-4 text-sm font-bold text-slate-800 text-right font-mono">
                                            {item.total_amount}
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className={`px-2 py-1 rounded-full text-xs font-semibold ${item.status === 'DRAFT' ? 'bg-gray-100 text-gray-700' :
                                                item.status === 'SENT' ? 'bg-blue-100 text-blue-700' :
                                                    item.status === 'ACCEPTED' ? 'bg-green-100 text-green-700' :
                                                        'bg-red-100 text-red-700'
                                                }`}>
                                                {item.status}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            <div className="flex justify-center gap-2">
                                                <button
                                                    onClick={() => {
                                                        setSelectedQuotation(item);
                                                        setViewModalOpen(true);
                                                    }}
                                                    className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-50 rounded-full transition-all"
                                                >
                                                    <FaEye />
                                                </button>
                                                <button
                                                    onClick={() => {
                                                        setSelectedQuotation(item);
                                                        setGstModalOpen(true);
                                                    }}
                                                    className="p-2 text-blue-600 hover:text-blue-800 hover:bg-blue-50 rounded-full transition-all disabled:opacity-30 disabled:cursor-not-allowed"
                                                    title="Update GST"
                                                    disabled={item.status !== 'DRAFT'}
                                                >
                                                    <FaEdit />
                                                </button>

                                                <button
                                                    onClick={() => handleStatusUpdate(item.id, 'SENT')}
                                                    disabled={item.status !== 'DRAFT'}
                                                    className="p-2 text-indigo-600 hover:text-indigo-800 hover:bg-indigo-50 rounded-full transition-all disabled:opacity-30 disabled:cursor-not-allowed"
                                                    title="Quotation Send"
                                                >
                                                    <FaPaperPlane />
                                                </button>
                                                <button
                                                    onClick={() => handleStatusUpdate(item.id, 'ACCEPTED')}
                                                    disabled={item.status !== 'SENT'}
                                                    className="p-2 text-green-600 hover:text-green-800 hover:bg-green-50 rounded-full transition-all disabled:opacity-30 disabled:cursor-not-allowed"
                                                    title="Quotation Accepted"
                                                >
                                                    <FaCheck />
                                                </button>
                                                <button
                                                    onClick={() => handleStatusUpdate(item.id, 'REJECTED')}
                                                    disabled={item.status !== 'SENT'}
                                                    className="p-2 text-red-600 hover:text-red-800 hover:bg-red-50 rounded-full transition-all disabled:opacity-30 disabled:cursor-not-allowed"
                                                    title="Quotation Rejected"
                                                >
                                                    <FaTimes />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan="7" className="px-6 py-6 text-center text-slate-500">
                                        No quotations found
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>

                {/* PAGINATION */}
                <div className="px-6 py-4 border-t border-slate-100 flex items-center justify-between">
                    <button
                        onClick={handlePrev}
                        disabled={!prevPage}
                        className="text-sm font-semibold text-slate-600 hover:text-blue-600 disabled:opacity-40 disabled:hover:text-slate-600 cursor-pointer disabled:cursor-not-allowed"
                    >
                        ← Previous
                    </button>

                    <span className="text-xs text-slate-400">Page {currentPage}</span>

                    <button
                        onClick={handleNext}
                        disabled={!nextPage}
                        className="text-sm font-semibold text-slate-600 hover:text-blue-600 disabled:opacity-40 disabled:hover:text-slate-600 cursor-pointer disabled:cursor-not-allowed"
                    >
                        Next →
                    </button>
                </div>
            </div>

            {/* MODAL */}
            <ClientQuotationModal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                onSuccess={() => {
                    fetchQuotations(currentPage, searchText, statusFilter);
                }}
            />

            {/* GST MODAL */}
            <UpdateGstModal
                isOpen={gstModalOpen}
                onClose={() => {
                    setGstModalOpen(false);
                    setSelectedQuotation(null);
                }}
                quotation={selectedQuotation}
                onSuccess={() => {
                    fetchQuotations(currentPage, searchText, statusFilter);
                }}
            />


            {/* DETAILS MODAL */}
            <ClientQuotationDetailsModal
                isOpen={viewModalOpen}
                onClose={() => {
                    setViewModalOpen(false);
                    setSelectedQuotation(null);
                }}
                quotation={selectedQuotation}
            />

            {/* CONFIRM DIALOG */}
            <ConfirmDialog
                open={confirmOpen}
                message={confirmMessage}
                onConfirm={confirmAction}
                onCancel={() => setConfirmOpen(false)}
                confirmText={confirmConfig.confirmText || "Yes, Proceed"}
                icon={confirmConfig.icon}
                confirmButtonClass={confirmConfig.confirmButtonClass}
                iconBgClass={confirmConfig.iconBgClass}
            />

            {/* ALERT TOAST */}
            <AlertToast
                open={alert.open}
                type={alert.type}
                message={alert.message}
                onClose={() => setAlert({ ...alert, open: false })}
            />

            {/* REPORT MODAL */}
            {showReportModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-sm overflow-hidden animate-in fade-in zoom-in-95 duration-200">
                        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50">
                            <h3 className="font-bold text-slate-800 flex items-center gap-2">
                                <FaFileExcel className="text-emerald-600" /> Generate Report
                            </h3>
                        </div>
                        <div className="p-6 space-y-4">
                            <div>
                                <label className="block text-xs font-semibold text-slate-600 mb-1">Start Date</label>
                                <input
                                    type="date"
                                    value={reportFilters.start_date}
                                    onChange={(e) => setReportFilters({ ...reportFilters, start_date: e.target.value })}
                                    className="input w-full"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-semibold text-slate-600 mb-1">End Date</label>
                                <input
                                    type="date"
                                    value={reportFilters.end_date}
                                    onChange={(e) => setReportFilters({ ...reportFilters, end_date: e.target.value })}
                                    className="input w-full"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-semibold text-slate-600 mb-1">Status Filter</label>
                                <select
                                    value={reportFilters.status}
                                    onChange={(e) => setReportFilters({ ...reportFilters, status: e.target.value })}
                                    className="input w-full"
                                >
                                    <option value="">All Status</option>
                                    <option value="DRAFT">Draft</option>
                                    <option value="SENT">Sent</option>
                                    <option value="ACCEPTED">Accepted</option>
                                    <option value="REJECTED">Rejected</option>
                                </select>
                            </div>

                            <div>
                                <label className="block text-xs font-semibold text-slate-600 mb-1">Report Type</label>
                                <select
                                    value={reportFilters.reportType}
                                    onChange={(e) => setReportFilters({ ...reportFilters, reportType: e.target.value })}
                                    className="input w-full"
                                >
                                    <option value="quotation_summary">Quotation Summary</option>
                                    <option value="item_analysis">Item Analysis</option>
                                </select>
                            </div>

                            {reportFilters.reportType === 'quotation_summary' && (
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">Status Filter</label>
                                    <select
                                        value={reportFilters.status}
                                        onChange={(e) => setReportFilters({ ...reportFilters, status: e.target.value })}
                                        className="input w-full"
                                    >
                                        <option value="">All Status</option>
                                        <option value="DRAFT">Draft</option>
                                        <option value="SENT">Sent</option>
                                        <option value="ACCEPTED">Accepted</option>
                                        <option value="REJECTED">Rejected</option>
                                    </select>
                                </div>
                            )}

                            {reportFilters.reportType === 'item_analysis' && (
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">Filter by Product</label>
                                    <ProductSelector
                                        value={reportFilters.product}
                                        onChange={(val) => setReportFilters({ ...reportFilters, product: val })}
                                        placeholder="Specific product (optional)"
                                    />
                                </div>
                            )}
                        </div>
                        <div className="px-6 py-4 border-t border-slate-100 flex justify-end gap-3 bg-slate-50">
                            <button
                                onClick={() => setShowReportModal(false)}
                                className="px-4 py-2 text-sm font-semibold text-slate-600 hover:text-slate-800"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={generateReport}
                                disabled={downloading}
                                className="px-4 py-2 bg-emerald-600 text-white text-sm font-semibold rounded-lg hover:bg-emerald-500 disabled:opacity-50 flex items-center gap-2"
                            >
                                {downloading ? "Downloading..." : "Download Excel"}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ClientQuotation;
