
import { useState, useEffect } from "react";
import { useSearchParams } from "react-router-dom";
import {
    Box,
    Card,
    Typography,
    Button,
    TextField,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    IconButton,
    Tooltip,
    CircularProgress,
    Chip,
    InputAdornment,
    MenuItem,
    Select,
    FormControl,
    InputLabel,
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
} from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import SearchIcon from "@mui/icons-material/Search";
import VisibilityIcon from "@mui/icons-material/Visibility";
import DescriptionIcon from "@mui/icons-material/Description";
import ChevronLeftIcon from "@mui/icons-material/ChevronLeft";
import ChevronRightIcon from "@mui/icons-material/ChevronRight";
import { getClientQueries, getClientQueryById, getClientQueryReport } from "../services/salesService";
import EnquiryModal from "../components/sales/EnquiryModal";
import EnquiryDetailsModal from "../components/sales/EnquiryDetailsModal";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

const statusChipProps = (status) => {
    switch (status) {
        case "PENDING":
            return { label: "PENDING", color: "warning" };
        case "QUOTATION_SENT":
            return { label: "QUOTATION SENT", color: "info" };
        case "CONVERTED":
            return { label: "CONVERTED", color: "success" };
        case "REJECTED":
            return { label: "REJECTED", color: "error" };
        default:
            return { label: status?.replace("_", " ") || "", color: "default" };
    }
};

const Enquiry = () => {
    const [searchText, setSearchText] = useState("");
    const [enquiries, setEnquiries] = useState([]);
    const [loading, setLoading] = useState(false);
    const [totalCount, setTotalCount] = useState(0);
    const [nextPage, setNextPage] = useState(null);
    const [prevPage, setPrevPage] = useState(null);
    const [currentPage, setCurrentPage] = useState(1);
    const [isModalOpen, setIsModalOpen] = useState(false);

    const [statusFilter, setStatusFilter] = useState("");
    const [searchParams] = useSearchParams();

    // View Modal State
    const [isViewModalOpen, setIsViewModalOpen] = useState(false);
    const [selectedEnquiry, setSelectedEnquiry] = useState(null);

    // Report Modal State
    const [showReportModal, setShowReportModal] = useState(false);
    const [downloading, setDownloading] = useState(false);
    const [reportFilters, setReportFilters] = useState({
        start_date: '',
        end_date: '',
        status: ''
    });

    const handleOpenReport = () => {
        const now = new Date();
        const firstDay = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0];
        const today = now.toISOString().split('T')[0];
        setReportFilters({ start_date: firstDay, end_date: today, status: '' });
        setShowReportModal(true);
    };

    const generateReport = async () => {
        setDownloading(true);
        try {
            const reportData = await getClientQueryReport(reportFilters);

            const wb = XLSX.utils.book_new();

            // Prepare Summary Data
            const summaryData = [
                ["CLIENT QUERY REPORT"],
                [],
                ["Generated By:", reportData.generated_by],
                ["Generated At:", new Date(reportData.generated_at).toLocaleString()],
                ["Date Range:", `${reportData.date_range?.start_date} to ${reportData.date_range?.end_date}`],
                [],
                ["SUMMARY STATISTICS"],
                ["Total Queries:", reportData.summary?.total_queries || 0],
                ["Pending Queries:", reportData.summary?.pending_queries || 0],
                ["Quotation Sent:", reportData.summary?.quotation_sent || 0],
                ["Converted:", reportData.summary?.converted_queries || 0],
                ["Rejected:", reportData.summary?.rejected_queries || 0],
                ["Conversion Rate:", reportData.summary?.conversion_rate || 0],
                [],
                ["DETAILED QUERIES"],
                ["Query No", "Date", "Client Name", "Contact Person", "Phone", "Email", "Status", "Sales Person"]
            ];

            // Add Query Rows
            if (reportData.queries && reportData.queries.length > 0) {
                reportData.queries.forEach(q => {
                    summaryData.push([
                        q.query_number,
                        q.query_date,
                        q.client_name || q.client?.name || "-",
                        q.contact_person || q.client?.contact_person || "-",
                        q.phone || q.client?.phone || "-",
                        q.email || q.client?.email || "-",
                        q.status,
                        q.created_by_name || q.created_by || "-"
                    ]);
                });
            } else {
                summaryData.push(["No queries found for this period."]);
            }

            const ws = XLSX.utils.aoa_to_sheet(summaryData);
            XLSX.utils.book_append_sheet(wb, ws, "Client Query Report");

            // Save
            const buffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
            const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8" });
            saveAs(blob, `Client_Query_Report_${reportFilters.start_date || 'all'}_to_${reportFilters.end_date || 'all'}.xlsx`);

            setShowReportModal(false);
        } catch (error) {
            console.error("Failed to generate report", error);
        } finally {
            setDownloading(false);
        }
    };

    const fetchEnquiries = async (page = 1, search = "", status = "") => {
        setLoading(true);
        try {
            const data = await getClientQueries(page, search, status);
            setEnquiries(data.results || []);
            setTotalCount(data.count || 0);
            setNextPage(data.next);
            setPrevPage(data.previous);
        } catch (error) {
            console.error("Failed to fetch enquiries", error);
        } finally {
            setLoading(false);
        }
    };

    // Initialize View ID and Status from URL
    useEffect(() => {
        const viewId = searchParams.get("view_id");
        const statusParam = searchParams.get("status");

        if (statusParam) {
            setStatusFilter(statusParam);
        }

        if (viewId) {
            const fetchDetail = async () => {
                try {
                    const data = await getClientQueryById(viewId);
                    setSelectedEnquiry(data);
                    setIsViewModalOpen(true);
                } catch (error) {
                    console.error("Failed to fetch enquiry details", error);
                }
            };
            fetchDetail();
        }
    }, [searchParams]);

    useEffect(() => {
        // Debounce search could be added here, but for now direct call on effect
        const timer = setTimeout(() => {
            fetchEnquiries(currentPage, searchText, statusFilter);
        }, 500);
        return () => clearTimeout(timer);
    }, [searchText, currentPage, statusFilter]);

    const handleSearch = (e) => {
        setSearchText(e.target.value);
        setCurrentPage(1); // Reset to first page on search
    };

    const handleNext = () => {
        if (nextPage) setCurrentPage((prev) => prev + 1);
    };

    const handlePrev = () => {
        if (prevPage) setCurrentPage((prev) => prev - 1);
    };

    const handleView = async (id) => {
        try {
            const data = await getClientQueryById(id);
            setSelectedEnquiry(data);
            setIsViewModalOpen(true);
        } catch (error) {
            console.error("Failed to fetch enquiry details", error);
        }
    };

    return (
        <Box>
            <Card
                sx={{
                    borderRadius: 4,
                    border: "1px solid",
                    borderColor: "slate.200",
                    boxShadow: 1,
                    overflow: "hidden",
                }}
            >
                {/* HEADER */}
                <Box
                    sx={{
                        px: 3,
                        py: 2,
                        borderBottom: "1px solid",
                        borderColor: "grey.200",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                    }}
                >
                    <Box>
                        <Typography variant="subtitle1" sx={{ fontWeight: 700, color: "grey.800" }}>
                            QUERY
                        </Typography>
                        <Typography variant="body2" sx={{ color: "grey.500", fontWeight: 600 }}>
                            Total: {totalCount}
                        </Typography>
                    </Box>

                    <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
                        <Button
                            variant="contained"
                            onClick={handleOpenReport}
                            startIcon={<DescriptionIcon />}
                            sx={{
                                bgcolor: "success.main",
                                textTransform: "none",
                                fontWeight: 600,
                                fontSize: "0.875rem",
                                borderRadius: 2,
                                "&:hover": { bgcolor: "success.dark" },
                            }}
                        >
                            Download Report
                        </Button>
                        <Button
                            variant="contained"
                            onClick={() => setIsModalOpen(true)}
                            startIcon={<AddIcon />}
                            sx={{
                                bgcolor: "primary.main",
                                textTransform: "none",
                                fontWeight: 600,
                                fontSize: "0.875rem",
                                borderRadius: 2,
                                "&:hover": { bgcolor: "primary.dark" },
                            }}
                        >
                            New Query
                        </Button>
                    </Box>
                </Box>

                {/* SEARCH & FILTER */}
                <Box
                    sx={{
                        px: 3,
                        py: 2,
                        borderBottom: "1px solid",
                        borderColor: "grey.200",
                        bgcolor: "grey.50",
                    }}
                >
                    <Box sx={{ display: "flex", flexWrap: "wrap", gap: 2, alignItems: "flex-end" }}>
                        {/* Status Filter */}
                        <FormControl size="small" sx={{ minWidth: 160 }}>
                            <InputLabel sx={{ fontSize: "0.75rem", fontWeight: 600 }}>Status</InputLabel>
                            <Select
                                value={statusFilter}
                                label="Status"
                                onChange={(e) => setStatusFilter(e.target.value)}
                                sx={{ bgcolor: "white" }}
                            >
                                <MenuItem value="">All Status</MenuItem>
                                <MenuItem value="PENDING">Pending</MenuItem>
                                <MenuItem value="QUOTATION_SENT">Quotation Sent</MenuItem>
                                <MenuItem value="CONVERTED">Converted</MenuItem>
                                <MenuItem value="REJECTED">Rejected</MenuItem>
                            </Select>
                        </FormControl>

                        {/* Search */}
                        <TextField
                            size="small"
                            value={searchText}
                            onChange={handleSearch}
                            placeholder="Search..."
                            label="Search Query"
                            sx={{ flex: 1, minWidth: 220, bgcolor: "white" }}
                            InputProps={{
                                startAdornment: (
                                    <InputAdornment position="start">
                                        <SearchIcon sx={{ color: "grey.400" }} />
                                    </InputAdornment>
                                ),
                            }}
                        />
                    </Box>
                </Box>

                {/* TABLE */}
                <TableContainer>
                    <Table>
                        <TableHead>
                            <TableRow sx={{ bgcolor: "primary.50", "& th": { fontWeight: 700, fontSize: "0.8125rem", color: "grey.800", textTransform: "uppercase", letterSpacing: "0.05em" } }}>
                                <TableCell sx={{ px: 3, py: 2 }}>Query No</TableCell>
                                <TableCell sx={{ px: 3, py: 2 }}>Date</TableCell>
                                <TableCell sx={{ px: 3, py: 2 }}>Customer</TableCell>
                                <TableCell sx={{ px: 3, py: 2 }}>Contact</TableCell>
                                <TableCell sx={{ px: 3, py: 2 }}>Status</TableCell>
                                <TableCell sx={{ px: 3, py: 2, textAlign: "center" }}>Actions</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {loading ? (
                                <TableRow>
                                    <TableCell colSpan={6} sx={{ textAlign: "center", py: 4 }}>
                                        <CircularProgress size={28} />
                                        <Typography variant="body2" sx={{ mt: 1, color: "grey.500" }}>
                                            Loading...
                                        </Typography>
                                    </TableCell>
                                </TableRow>
                            ) : enquiries.length > 0 ? (
                                enquiries.map((item, index) => (
                                    <TableRow
                                        key={item.id}
                                        sx={{
                                            bgcolor: index % 2 === 0 ? "grey.100" : "white",
                                            "&:hover": { bgcolor: "grey.200" },
                                            transition: "background-color 0.15s",
                                        }}
                                    >
                                        <TableCell sx={{ px: 3, py: 2, fontFamily: "monospace", color: "primary.main", fontWeight: 600 }}>
                                            {item.query_number}
                                        </TableCell>
                                        <TableCell sx={{ px: 3, py: 2 }}>
                                            <Typography variant="body2" sx={{ color: "grey.600" }}>
                                                {item.query_date}
                                            </Typography>
                                        </TableCell>
                                        <TableCell sx={{ px: 3, py: 2 }}>
                                            <Typography variant="body2" sx={{ fontWeight: 500, color: "grey.800" }}>
                                                {item.client_name}
                                            </Typography>
                                            <Typography variant="caption" sx={{ color: "grey.500" }}>
                                                {item.address}
                                            </Typography>
                                        </TableCell>
                                        <TableCell sx={{ px: 3, py: 2 }}>
                                            <Typography variant="body2" sx={{ color: "grey.700" }}>
                                                {item.contact_person}
                                            </Typography>
                                            <Typography variant="caption" sx={{ color: "grey.500" }}>
                                                {item.phone}
                                            </Typography>
                                        </TableCell>
                                        <TableCell sx={{ px: 3, py: 2 }}>
                                            <Chip
                                                size="small"
                                                {...statusChipProps(item.status)}
                                            />
                                        </TableCell>
                                        <TableCell sx={{ px: 3, py: 2, textAlign: "center" }}>
                                            <Tooltip title="View Details">
                                                <IconButton
                                                    size="small"
                                                    onClick={() => handleView(item.id)}
                                                    sx={{ color: "primary.main" }}
                                                >
                                                    <VisibilityIcon fontSize="small" />
                                                </IconButton>
                                            </Tooltip>
                                        </TableCell>
                                    </TableRow>
                                ))
                            ) : (
                                <TableRow>
                                    <TableCell colSpan={6} sx={{ textAlign: "center", py: 4, color: "grey.500" }}>
                                        No data found
                                    </TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </TableContainer>

                {/* PAGINATION */}
                <Box
                    sx={{
                        px: 3,
                        py: 2,
                        borderTop: "1px solid",
                        borderColor: "grey.200",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                    }}
                >
                    <Button
                        size="small"
                        onClick={handlePrev}
                        disabled={!prevPage}
                        startIcon={<ChevronLeftIcon />}
                        sx={{
                            textTransform: "none",
                            fontWeight: 600,
                            fontSize: "0.875rem",
                            color: "grey.600",
                            "&:hover": { color: "primary.main" },
                        }}
                    >
                        Previous
                    </Button>

                    <Typography variant="caption" sx={{ color: "grey.400" }}>
                        Page {currentPage}
                    </Typography>

                    <Button
                        size="small"
                        onClick={handleNext}
                        disabled={!nextPage}
                        endIcon={<ChevronRightIcon />}
                        sx={{
                            textTransform: "none",
                            fontWeight: 600,
                            fontSize: "0.875rem",
                            color: "grey.600",
                            "&:hover": { color: "primary.main" },
                        }}
                    >
                        Next
                    </Button>
                </Box>
            </Card>

            {/* Modal */}
            <EnquiryModal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                onSuccess={() => fetchEnquiries(currentPage, searchText, statusFilter)}
            />

            {/* View Details Modal */}
            <EnquiryDetailsModal
                isOpen={isViewModalOpen}
                onClose={() => setIsViewModalOpen(false)}
                enquiry={selectedEnquiry}
            />

            {/* Report Modal */}
            <Dialog
                open={showReportModal}
                onClose={() => setShowReportModal(false)}
                maxWidth="xs"
                fullWidth
                PaperProps={{
                    sx: { borderRadius: 3, overflow: "hidden" },
                }}
            >
                <DialogTitle
                    sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: 1,
                        bgcolor: "grey.50",
                        borderBottom: "1px solid",
                        borderColor: "grey.200",
                        fontWeight: 700,
                        color: "grey.800",
                        py: 2,
                        px: 3,
                    }}
                >
                    <DescriptionIcon sx={{ color: "success.main" }} />
                    Generate Report
                </DialogTitle>
                <DialogContent sx={{ p: 3, display: "flex", flexDirection: "column", gap: 2.5, pt: "20px !important" }}>
                    <TextField
                        label="Start Date"
                        type="date"
                        size="small"
                        fullWidth
                        value={reportFilters.start_date}
                        onChange={(e) => setReportFilters({ ...reportFilters, start_date: e.target.value })}
                        InputLabelProps={{ shrink: true }}
                    />
                    <TextField
                        label="End Date"
                        type="date"
                        size="small"
                        fullWidth
                        value={reportFilters.end_date}
                        onChange={(e) => setReportFilters({ ...reportFilters, end_date: e.target.value })}
                        InputLabelProps={{ shrink: true }}
                    />
                    <FormControl size="small" fullWidth>
                        <InputLabel>Status Filter</InputLabel>
                        <Select
                            value={reportFilters.status}
                            label="Status Filter"
                            onChange={(e) => setReportFilters({ ...reportFilters, status: e.target.value })}
                        >
                            <MenuItem value="">All Status</MenuItem>
                            <MenuItem value="PENDING">Pending</MenuItem>
                            <MenuItem value="QUOTATION_SENT">Quotation Sent</MenuItem>
                            <MenuItem value="CONVERTED">Converted</MenuItem>
                            <MenuItem value="REJECTED">Rejected</MenuItem>
                        </Select>
                    </FormControl>
                </DialogContent>
                <DialogActions
                    sx={{
                        px: 3,
                        py: 2,
                        borderTop: "1px solid",
                        borderColor: "grey.200",
                        bgcolor: "grey.50",
                    }}
                >
                    <Button
                        onClick={() => setShowReportModal(false)}
                        sx={{
                            textTransform: "none",
                            fontWeight: 600,
                            color: "grey.600",
                            "&:hover": { color: "grey.800" },
                        }}
                    >
                        Cancel
                    </Button>
                    <Button
                        variant="contained"
                        onClick={generateReport}
                        disabled={downloading}
                        startIcon={downloading ? <CircularProgress size={16} color="inherit" /> : null}
                        sx={{
                            bgcolor: "success.main",
                            textTransform: "none",
                            fontWeight: 600,
                            borderRadius: 2,
                            "&:hover": { bgcolor: "success.dark" },
                        }}
                    >
                        {downloading ? "Downloading..." : "Download Excel"}
                    </Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
};

export default Enquiry;
