
import { useState, useEffect } from "react";
import { useSearchParams } from "react-router-dom";
import { FaPlus, FaSearch, FaEye, FaFileExcel } from "react-icons/fa";
import { getClientQueries, getClientQueryById, getClientQueryReport } from "../services/salesService";
import EnquiryModal from "../components/sales/EnquiryModal";
import EnquiryDetailsModal from "../components/sales/EnquiryDetailsModal";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

const Enquiry = () => {
    const [searchText, setSearchText] = useState("");
    const [enquiries, setEnquiries] = useState([]);
    const [loading, setLoading] = useState(false);
    const [totalCount, setTotalCount] = useState(0);
    const [nextPage, setNextPage] = useState(null);
    const [prevPage, setPrevPage] = useState(null);
    const [currentPage, setCurrentPage] = useState(1);
    const [isModalOpen, setIsModalOpen] = useState(false);

    const [statusFilter, setStatusFilter] = useState("");
    const [searchParams] = useSearchParams();

    // View Modal State
    const [isViewModalOpen, setIsViewModalOpen] = useState(false);
    const [selectedEnquiry, setSelectedEnquiry] = useState(null);

    // Report Modal State
    const [showReportModal, setShowReportModal] = useState(false);
    const [downloading, setDownloading] = useState(false);
    const [reportFilters, setReportFilters] = useState({
        start_date: '',
        end_date: '',
        status: ''
    });

    const handleOpenReport = () => {
        const now = new Date();
        const firstDay = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0];
        const today = now.toISOString().split('T')[0];
        setReportFilters({ start_date: firstDay, end_date: today, status: '' });
        setShowReportModal(true);
    };

    const generateReport = async () => {
        setDownloading(true);
        try {
            const reportData = await getClientQueryReport(reportFilters);

            const wb = XLSX.utils.book_new();

            // Prepare Summary Data
            const summaryData = [
                ["CLIENT QUERY REPORT"],
                [],
                ["Generated By:", reportData.generated_by],
                ["Generated At:", new Date(reportData.generated_at).toLocaleString()],
                ["Date Range:", `${reportData.date_range?.start_date} to ${reportData.date_range?.end_date}`],
                [],
                ["SUMMARY STATISTICS"],
                ["Total Queries:", reportData.summary?.total_queries || 0],
                ["Pending Queries:", reportData.summary?.pending_queries || 0],
                ["Quotation Sent:", reportData.summary?.quotation_sent || 0],
                ["Converted:", reportData.summary?.converted_queries || 0],
                ["Rejected:", reportData.summary?.rejected_queries || 0],
                ["Conversion Rate:", reportData.summary?.conversion_rate || 0],
                [],
                ["DETAILED QUERIES"],
                ["Query No", "Date", "Client Name", "Contact Person", "Phone", "Email", "Status", "Sales Person"]
            ];

            // Add Query Rows
            if (reportData.queries && reportData.queries.length > 0) {
                reportData.queries.forEach(q => {
                    summaryData.push([
                        q.query_number,
                        q.query_date,
                        q.client_name || q.client?.name || "-",
                        q.contact_person || q.client?.contact_person || "-",
                        q.phone || q.client?.phone || "-",
                        q.email || q.client?.email || "-",
                        q.status,
                        q.created_by_name || q.created_by || "-"
                    ]);
                });
            } else {
                summaryData.push(["No queries found for this period."]);
            }

            const ws = XLSX.utils.aoa_to_sheet(summaryData);
            XLSX.utils.book_append_sheet(wb, ws, "Client Query Report");

            // Save
            const buffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
            const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8" });
            saveAs(blob, `Client_Query_Report_${reportFilters.start_date || 'all'}_to_${reportFilters.end_date || 'all'}.xlsx`);

            setShowReportModal(false);
        } catch (error) {
            console.error("Failed to generate report", error);
        } finally {
            setDownloading(false);
        }
    };

    const fetchEnquiries = async (page = 1, search = "", status = "") => {
        setLoading(true);
        try {
            const data = await getClientQueries(page, search, status);
            setEnquiries(data.results || []);
            setTotalCount(data.count || 0);
            setNextPage(data.next);
            setPrevPage(data.previous);
        } catch (error) {
            console.error("Failed to fetch enquiries", error);
        } finally {
            setLoading(false);
        }
    };

    // Initialize View ID and Status from URL
    useEffect(() => {
        const viewId = searchParams.get("view_id");
        const statusParam = searchParams.get("status");

        if (statusParam) {
            setStatusFilter(statusParam);
        }

        if (viewId) {
            const fetchDetail = async () => {
                try {
                    const data = await getClientQueryById(viewId);
                    setSelectedEnquiry(data);
                    setIsViewModalOpen(true);
                } catch (error) {
                    console.error("Failed to fetch enquiry details", error);
                }
            };
            fetchDetail();
        }
    }, [searchParams]);

    useEffect(() => {
        // Debounce search could be added here, but for now direct call on effect
        const timer = setTimeout(() => {
            fetchEnquiries(currentPage, searchText, statusFilter);
        }, 500);
        return () => clearTimeout(timer);
    }, [searchText, currentPage, statusFilter]);

    const handleSearch = (e) => {
        setSearchText(e.target.value);
        setCurrentPage(1); // Reset to first page on search
    };

    const handleNext = () => {
        if (nextPage) setCurrentPage((prev) => prev + 1);
    };

    const handlePrev = () => {
        if (prevPage) setCurrentPage((prev) => prev - 1);
    };

    const handleView = async (id) => {
        try {
            const data = await getClientQueryById(id);
            setSelectedEnquiry(data);
            setIsViewModalOpen(true);
        } catch (error) {
            console.error("Failed to fetch enquiry details", error);
        }
    };

    return (
        <div>
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
                {/* HEADER */}
                <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
                    <div>
                        <h3 className="font-bold text-slate-800">QUERY</h3>
                        <span className="text-sm text-slate-500 font-semibold">
                            Total: {totalCount}
                        </span>
                    </div>

                    <div className="flex items-center gap-3">
                        <button
                            onClick={handleOpenReport}
                            className="flex items-center gap-2 px-4 py-2 bg-emerald-600 text-white text-sm font-semibold rounded-lg hover:bg-emerald-500"
                        >
                            <FaFileExcel className="text-sm" />
                            Download Report
                        </button>
                        <button
                            onClick={() => setIsModalOpen(true)}
                            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-500"
                        >
                            <FaPlus className="text-xs" />
                            New Query
                        </button>
                    </div>
                </div>

                {/* SEARCH & FILTER */}
                <div className="px-6 py-4 border-b border-slate-100 bg-slate-50">
                    <div className="flex flex-wrap gap-4 items-end">
                        {/* Status Filter */}
                        <div className="w-40">
                            <label className="block text-xs font-semibold text-slate-600 mb-1">
                                Status
                            </label>
                            <select
                                value={statusFilter}
                                onChange={(e) => setStatusFilter(e.target.value)}
                                className="input w-full"
                            >
                                <option value="">All Status</option>
                                <option value="PENDING">Pending</option>
                                <option value="QUOTATION_SENT">Quotation Sent</option>
                                <option value="CONVERTED">Converted</option>
                                <option value="REJECTED">Rejected</option>
                            </select>
                        </div>

                        {/* Search */}
                        <div className="flex-1 min-w-55">
                            <label className="block text-xs font-semibold text-slate-600 mb-1">
                                Search Query
                            </label>
                            <div className="relative">
                                <input
                                    value={searchText}
                                    onChange={handleSearch}
                                    placeholder="Search..."
                                    className="w-full pl-10 pr-4 py-2 bg-white border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                                />
                                <FaSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-blue-50/50 text-slate-800 uppercase text-[10px] font-bold tracking-widest">
                            <th className="px-6 py-4 text-[13px]">Query No</th>
                            <th className="px-6 py-4 text-[13px]">Date</th>
                            <th className="px-6 py-4 text-[13px]">Customer</th>
                            <th className="px-6 py-4 text-[13px]">Contact</th>
                            <th className="px-6 py-4 text-[13px]">Status</th>
                            <th className="px-6 py-4 text-[13px] text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {loading ? (
                            <tr>
                                <td colSpan="6" className="px-6 py-6 text-center text-slate-500">
                                    Loading...
                                </td>
                            </tr>
                        ) : enquiries.length > 0 ? (
                            enquiries.map((item) => (
                                <tr key={item.id} className="hover:bg-slate-50/50 transition-colors">
                                    <td className="px-6 py-4 font-mono text-blue-600 font-semibold">
                                        {item.query_number}
                                    </td>
                                    <td className="px-6 py-4 text-sm text-slate-600">
                                        {item.query_date}
                                    </td>
                                    <td className="px-6 py-4">
                                        <div className="text-sm font-medium text-slate-800">
                                            {item.client_name}
                                        </div>
                                        <div className="text-xs text-slate-500">
                                            {item.address}
                                        </div>
                                    </td>
                                    <td className="px-6 py-4">
                                        <div className="text-sm text-slate-700">
                                            {item.contact_person}
                                        </div>
                                        <div className="text-xs text-slate-500">
                                            {item.phone}
                                        </div>
                                    </td>
                                    <td className="px-6 py-4">
                                        <span className={`px-2 py-1 rounded-full text-xs font-semibold ${item.status === 'PENDING' ? 'bg-yellow-100 text-yellow-700' :
                                            item.status === 'QUOTATION_SENT' ? 'bg-blue-100 text-blue-700' :
                                                item.status === 'CONVERTED' ? 'bg-green-100 text-green-700' :
                                                    item.status === 'REJECTED' ? 'bg-red-100 text-red-700' :
                                                        'bg-slate-100 text-slate-700'
                                            }`}>
                                            {item.status?.replace('_', ' ')}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4 text-center">
                                        <button
                                            onClick={() => handleView(item.id)}
                                            className="text-blue-600 hover:text-blue-800 text-sm font-medium"
                                        >
                                            <FaEye />
                                        </button>
                                    </td>
                                </tr>
                            ))
                        ) : (
                            <tr>
                                <td colSpan="6" className="px-6 py-6 text-center text-slate-500">
                                    No data found
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>

            {/* PAGINATION */}
            <div className="px-6 py-4 border-t border-slate-100 flex items-center justify-between">
                <button
                    onClick={handlePrev}
                    disabled={!prevPage}
                    className="text-sm font-semibold text-slate-600 hover:text-blue-600 disabled:opacity-40 disabled:hover:text-slate-600 cursor-pointer disabled:cursor-not-allowed"
                >
                    ← Previous
                </button>

                <span className="text-xs text-slate-400">Page {currentPage}</span>

                <button
                    onClick={handleNext}
                    disabled={!nextPage}
                    className="text-sm font-semibold text-slate-600 hover:text-blue-600 disabled:opacity-40 disabled:hover:text-slate-600 cursor-pointer disabled:cursor-not-allowed"
                >
                    Next →
                </button>
            </div>
            {/* Modal */}
            <EnquiryModal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                onSuccess={() => fetchEnquiries(currentPage, searchText, statusFilter)}
            />

            {/* View Details Modal */}
            <EnquiryDetailsModal
                isOpen={isViewModalOpen}
                onClose={() => setIsViewModalOpen(false)}
                enquiry={selectedEnquiry}
            />

            {/* Report Modal */}
            {showReportModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-sm overflow-hidden animate-in fade-in zoom-in-95 duration-200">
                        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50">
                            <h3 className="font-bold text-slate-800 flex items-center gap-2">
                                <FaFileExcel className="text-emerald-600" /> Generate Report
                            </h3>
                        </div>
                        <div className="p-6 space-y-4">
                            <div>
                                <label className="block text-xs font-semibold text-slate-600 mb-1">Start Date</label>
                                <input
                                    type="date"
                                    value={reportFilters.start_date}
                                    onChange={(e) => setReportFilters({ ...reportFilters, start_date: e.target.value })}
                                    className="input w-full"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-semibold text-slate-600 mb-1">End Date</label>
                                <input
                                    type="date"
                                    value={reportFilters.end_date}
                                    onChange={(e) => setReportFilters({ ...reportFilters, end_date: e.target.value })}
                                    className="input w-full"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-semibold text-slate-600 mb-1">Status Filter</label>
                                <select
                                    value={reportFilters.status}
                                    onChange={(e) => setReportFilters({ ...reportFilters, status: e.target.value })}
                                    className="input w-full"
                                >
                                    <option value="">All Status</option>
                                    <option value="PENDING">Pending</option>
                                    <option value="QUOTATION_SENT">Quotation Sent</option>
                                    <option value="CONVERTED">Converted</option>
                                    <option value="REJECTED">Rejected</option>
                                </select>
                            </div>
                        </div>
                        <div className="px-6 py-4 border-t border-slate-100 flex justify-end gap-3 bg-slate-50">
                            <button
                                onClick={() => setShowReportModal(false)}
                                className="px-4 py-2 text-sm font-semibold text-slate-600 hover:text-slate-800"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={generateReport}
                                disabled={downloading}
                                className="px-4 py-2 bg-emerald-600 text-white text-sm font-semibold rounded-lg hover:bg-emerald-500 disabled:opacity-50 flex items-center gap-2"
                            >
                                {downloading ? "Downloading..." : "Download Excel"}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Enquiry;
